language: minimal

sudo: required

services:
  - docker  

jobs:
  include:
    - script: |
        # TODO - how to get performance folder from current gh-pages to not get overwritten. Do we need to clone branch & copy it in?
        docker build -t ${TRAVIS_BUILD_DIR}/docker/gasnet-experimental/
        docker run -it -v ${TRAVIS_BUILD_DIR}:/repo.git -w /repo.git -d gasnet-experimental /bin/bash -c '
        pushd $CHPL_HOME
        . util/setchplenv.sh
        popd
        chpldoc src/*.chpl
        touch docs/.nojekyll
        cd test
        chpl --version
        start_test -junit-xml -numlocales 4'

deploy:
    provider: pages
    local_dir: ${TRAVIS_BUILD_DIR}/docs
    target_branch: gh-pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set as a Travis-CI env variable
    keep_history: true
    on:
        branch: master        

notifications:
    slack: hypergraphs:D6dV0BOxuu3GjVNcp3jokIXb
